version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: tasks
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1111
      DB_NAME: tasks
      DB_PORT: 5432
      DB_DIALECT: postgres
      JWT_SECRET_KEY: passwordñ
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db-data:
